--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekRulesUI
build-by-default: true
branches:
- stable
- pm4
projects:
  KygekRulesUI:
    path: ""
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.0.0
    - src: KygekTeam/ktpmpl-cfs/ktpmpl-cfs
      branch: pm4
      version: ^2.0
    lint:
      phpstan: false
...
